version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    image: screamoff/foodgram-frontend:latest
    volumes:
      - frontend:/app/result_build/
    depends_on:
      - db
  backend:
    image: screamoff/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media_backend/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media_backend/
    depends_on:
      - backend
      - frontend

volumes:
  frontend:
  database:
  static_value:
  media_value: