# Generated by Django 4.1.7 on 2023-03-09 16:03
import json

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

with open('ingredients.json', 'r') as file:
    data = json.load(file)


def add_ingredients(apps, schema_editor):
    ingredient_model = apps.get_model('recipes', 'Ingredient')
    for ingredient in data:
        new_ingredient = ingredient_model(**ingredient)
        new_ingredient.save()


def remove_ingredients(apps, schema_editor):  # pragma: no cover
    ingredient_model = apps.get_model('recipes', 'Ingredient')
    for ingredient in data:
        try:
            ingredient_model.objects.get(**ingredient).delete()
        except ObjectDoesNotExist:
            print(f"Ingredient {ingredient.get('name')} "
                  f"doesn't exists. Skipped.")


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_ingredients, remove_ingredients)
    ]
