# Generated by Django 4.1.7 on 2023-03-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favorite_cart_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
